[package]
name = "event_sender"
version = "0.1.0"
edition = "2018"

[dependencies]
eiffelvis_gen = { version = "0.1", path = "../../crates/eiffelvis_gen"}
lapin = "1.8.0"
tokio-amqp = "1.0"
tokio = { version = "1.0", features = ["full"]}
anyhow = "1.0"
structopt = { version = "0.3", default-features = false }