[package]
name = "eiffelvis_core"
version = "0.1.0"
edition = "2018"

[dependencies]
indexmap = "1.7.0"
serde = { version="1.0", features=["derive"]}
uuid = { version = "0.8", features=["serde", "v4"]}
