name: Docker image
on:
  push:
    paths:
      - deployment/**
      - Dockerfile
  release: null
jobs:
  dockerfile:
    name: Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
